from .ga_hyperparameter_optimizer_test import ga_hyperparameter_optimizer_test
from .linear_regression_test import test_linear_regression
from .logistic_regression_test import test_logistic_regression
from .naive_bayes_test import test_naive_bayes
from .main_model_tests import main_model_tests