from tests.linear_regression_test import linear_regression_test
from tests.logistic_regression_test import logistic_regression_test
from tests.naive_bayes_test import naive_bayes_test
from tests.ga_hyperparameter_optimizer_test import ga_hyperparameter_optimizer_test

def run_all_tests():
    return ga_hyperparameter_optimizer_test()