from models.linear_regression.linear_regression import LinearRegression
from models.logistic_regression.logistic_regression import LogisticRegression
from models.naive_bayes.naive_bayes import NaiveBayes